"""create student table

Revision ID: 35e0895d3594
Revises: 1ddaa1d3a0b7
Create Date: 2025-10-07 11:50:04.618962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e0895d3594'
down_revision = '1ddaa1d3a0b7'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False, unique=True),  # one-to-one
        sa.Column("enrollment_date", sa.String(), nullable=False),
        sa.Column("min_course_credits", sa.String(), nullable=False),
        sa.Column("last_login", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student")
    # ### end Alembic commands ###
